# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pets

pod 'YandexMapsMobile', '4.0.0-full'

  target 'PetsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PetsUITests' do
    # Pods for testing
  end

end
